# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Create Github Issue
      # You may pin to the exact commit or the version.
      # uses: dacbd/create-issue-action@ba4d1c45cccf9c483f2720cefb40e437f0ee6f7d
      uses: dacbd/create-issue-action@v1.2.1
      with:
        # Your Github PAT, defaults to actions token
        token: # optional
        # Repo Owner, if not set implied by context.
        owner: # optional
        # Repo or impiled by the current context
        repo: # optional
        # Issue title
        title: This is the title
        # Body content of issue
        body: # optional
        # Milestone associated with issue
        milestone: # optional
        # CSV of labels (e.x. 'p0-critial,bug,aws')
        labels: # optional
        # CSV of github usernames to assign (e.x. 'dacbd,nlf')
        assignees: # optional

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
